=== IIpocToIIapeHb/XMLForPhilip/data_xml/bankDeposits.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/bankDeposits"
        xmlns:tns="http://www.example.com/bankDeposits" elementFormDefault="qualified">


    <element name="bank-deposit" type="tns:BankDeposit" abstract="true"/>
    <element name="individual-deposit" type="tns:IndividualDeposit" substitutionGroup="tns:bank-deposit"/>
    <element name="fixed-termed-deposit" type="tns:FixedTermedDeposit"
             substitutionGroup="tns:bank-deposit"/>
    <element name="legal-entity-deposit" type="tns:LegalEntityDeposit"
             substitutionGroup="tns:bank-deposit"/>

    <element name="bank-deposits">
        <complexType>
            <sequence>
                <element ref="tns:bank-deposit" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="BankDeposit">
        <sequence>
            <element name="bank-name" type="string"/>
            <element name="amount" type="int"/>
            <element name="percent" type="int"/>
        </sequence>
        <attribute name="id"  type="tns:Id"  use="required"/>
        <attribute name="country" type="string" use="optional" default="Earth"/>
        <attribute name="currency" use="required" >
            <simpleType>
                <restriction base="string">
                    <enumeration value="EURO"/>
                    <enumeration value="DOLLAR"/>
                    <enumeration value="YUAN"/>
                    <enumeration value="BEL_RUBLE"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="IndividualDeposit">
        <complexContent>
            <extension base="tns:BankDeposit">
                <sequence>
                    <element name="depositor-name" type="string"/>
                    <element name="depositor-surname" type="string"/>
                    <element name="passport-number" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="FixedTermedDeposit">
        <complexContent>
            <extension base="tns:IndividualDeposit">
                <sequence>
                    <element name="number-of-years" type="int"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="LegalEntityDeposit">
        <complexContent>
            <extension base="tns:BankDeposit">
                <sequence>
                    <element name="company-name" type="string"/>
                    <element name="number-of-founders" type="int"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name = "Id">
        <restriction base="ID">
            <pattern value="([a-zA-Z])[a-zA-Z0-9]{7,19}"/>
        </restriction>
    </simpleType>
</schema>

=== IIpocToIIapeHb/XMLForPhilip/data_xml/bankDeposits.xml
<?xml version="1.0" encoding="UTF-8"?>
<bank-deposits xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://www.example.com/bankDeposits"
               xsi:schemaLocation="http://www.example.com/bankDeposits  bankDeposits.xsd">

    <individual-deposit id="GE0M354123" country="China" currency = "EURO">
        <bank-name>JPMorganChase</bank-name>
        <amount>10000</amount>
        <percent>5</percent>
        <depositor-name>Adolf</depositor-name>
        <depositor-surname>Hittler</depositor-surname>
        <passport-number>kh1111</passport-number>
    </individual-deposit>

    <individual-deposit id="GE0M34123" currency = "EURO">
        <bank-name>HSBC</bank-name>
        <amount>1000</amount>
        <percent>10</percent>
        <depositor-name>Eric</depositor-name>
        <depositor-surname>Browser</depositor-surname>
        <passport-number>mp2222</passport-number>
    </individual-deposit>

    <fixed-termed-deposit id="a333vvB3" country="USA" currency = "DOLLAR">
        <bank-name>BankOfAmerica</bank-name>
        <amount>50000</amount>
        <percent>1</percent>
        <depositor-name>Oscar</depositor-name>
        <depositor-surname>Coul</depositor-surname>
        <passport-number>mp3333</passport-number>
        <number-of-years>5</number-of-years>
    </fixed-termed-deposit>

    <fixed-termed-deposit id="n4444444" currency = "YUAN">
        <bank-name>	BankofChina</bank-name>
        <amount>50000</amount>
        <percent>2</percent>
        <depositor-name>Julia</depositor-name>
        <depositor-surname>Shelf</depositor-surname>
        <passport-number>mp44444</passport-number>
        <number-of-years>3</number-of-years>
    </fixed-termed-deposit>

    <legal-entity-deposit id="HJ555555" currency = "DOLLAR">
        <bank-name>BankofSpain</bank-name>
        <amount>9000</amount>
        <percent>3</percent>
        <company-name>Bubbles</company-name>
        <number-of-founders>2</number-of-founders>
    </legal-entity-deposit>

    <legal-entity-deposit id="lF666666" country="Canada" currency = "DOLLAR">
        <bank-name>RoyalBankofCanada</bank-name>
        <amount>2500</amount>
        <percent>4</percent>
        <company-name>Umbrella</company-name>
        <number-of-founders>500</number-of-founders>
    </legal-entity-deposit>

</bank-deposits>
