=== IIpocToIIapeHb/XMLForPhilip/data/bankDeposits.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.epam.tc.com/bankDeposit"
           xmlns:tns="http://www.epam.tc.com/bankDeposit">

    <xs:element name="bankDeposit" type="tns:BankDeposit" abstract="true"/>
    <xs:element name="individualDeposit" type="tns:IndividualDeposit" substitutionGroup="tns:bankDeposit"/>
    <xs:element name="fixedTermedDeposit" type="tns:FixedTermedDeposit"
                substitutionGroup="tns:bankDeposit"/>
    <xs:element name="legalEntityDeposit" type="tns:LegalEntityDeposit"
                substitutionGroup="tns:bankDeposit"/>

    <xs:element name="bankDeposits">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:bankDeposit" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="BankDeposit">
        <xs:sequence>
            <xs:element name="bankName" type="xs:string"/>
            <xs:element name="amount" type="xs:int"/>
            <xs:element name="percent" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="id"  type="tns:Id"  use="required"/>
        <xs:attribute name="country" type="xs:string" use="optional"/>
        <xs:attribute name="currency" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="EURO"/>
                    <xs:enumeration value="DOLLAR"/>
                    <xs:enumeration value="YUAN"/>
                    <xs:enumeration value="BEL_RUBLE"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name = "Id">
        <xs:restriction base="xs:ID">
            <xs:pattern value="(\\d){5,10}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="IndividualDeposit">
        <xs:complexContent>
            <xs:extension base="tns:BankDeposit">
                <xs:sequence>
                    <xs:element name="depositorName" type="xs:string"/>
                    <xs:element name="depositorSurname" type="xs:string"/>
                    <xs:element name="passportNumber" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="FixedTermedDeposit">
        <xs:complexContent>
            <xs:extension base="tns:IndividualDeposit">
                <xs:sequence>
                    <xs:element name="numberOfYears" type="xs:int"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="LegalEntityDeposit">
        <xs:complexContent>
            <xs:extension base="tns:BankDeposit">
                <xs:sequence>
                    <xs:element name="companyName" type="xs:string"/>
                    <xs:element name="numberOfFounders" type="xs:int"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== IIpocToIIapeHb/XMLForPhilip/data/bankDeposits.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<bankDeposits  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.epam.tc.com/bankDeposit"
         xsi:schemaLocation="http://www.epam.tc.com/bankDeposit bankDeposits.xsd">

    <individualDeposit id="111111" currency = "EURO">
        <bankName>JPMorganChase</bankName>
        <amount>10000</amount>
        <percent>5</percent>
        <depositorName>Adolf</depositorName>
        <depositorSurname>Hittler</depositorSurname>
        <passportNumber>kh1111</passportNumber>
    </individualDeposit>

    <individualDeposit id="222222" country="UK" currency = "EURO">
        <bankName>HSBC</bankName>
        <amount>1000</amount>
        <percent>10</percent>
        <depositorName>Eric</depositorName>
        <depositorSurname>Browser</depositorSurname>
        <passportNumber>mp2222</passportNumber>
    </individualDeposit>

    <fixedTermedDeposit id="333333" country="USA" currency = "DOLLAR">
        <bankName>BankOfAmerica</bankName>
        <amount>50000</amount>
        <percent>1</percent>
        <depositorName>Oscar</depositorName>
        <depositorSurname>Coul</depositorSurname>
        <passportNumber>mp3333</passportNumber>
        <numberOfYears>5</numberOfYears>
    </fixedTermedDeposit>

    <fixedTermedDeposit id="444444"  currency = "YUAN">
        <bankName>	BankofChina</bankName>
        <amount>50000</amount>
        <percent>2</percent>
        <depositorName>Julia</depositorName>
        <depositorSurname>Shelf</depositorSurname>
        <passportNumber>mp44444</passportNumber>
        <numberOfYears>3</numberOfYears>
    </fixedTermedDeposit>

    <legalEntityDeposit id="555555"  currency = "DOLLAR">
        <bankName>BankofSpain</bankName>
        <amount>9000</amount>
        <percent>3</percent>
        <companyName>Bubbles</companyName>
        <numberOfFounders>2</numberOfFounders>
    </legalEntityDeposit>

    <legalEntityDeposit id="666666" country="Canada"  currency = "DOLLAR">
        <bankName>RoyalBankofCanada</bankName>
        <amount>2500</amount>
        <percent>4</percent>
        <companyName>Umbrella</companyName>
        <numberOfFounders>500</numberOfFounders>
    </legalEntityDeposit>

</bankDeposits>
